// Shared by tool/generate_curriculum_seed.dart and its drift test.

const curriculumDefinitionPath = 'supabase/curriculum/journey-metadata.json';
const curriculumSeedPath = 'supabase/seed_curriculum.sql';

/// Line endings as LF. A Windows checkout with core.autocrlf turns the
/// committed LF files into CRLF in the working tree; the content is the same.
String normalizeLineEndings(String text) => text.replaceAll('\r\n', '\n');

/// The seed SQL that publishes [definitionJson] for the local church as a
/// METADATA publication (ADR-019 decision 2), published by the local admin.
///
/// Always LF, whatever the line endings of [definitionJson], so the output
/// is the same on every platform.
String curriculumSeedSql(String definitionJson) {
  definitionJson = normalizeLineEndings(definitionJson);
  // Dollar quoting keeps the JSON verbatim; the tag cannot occur in it.
  const tag = r'$curriculum$';
  if (definitionJson.contains(tag)) {
    throw ArgumentError('The definition contains $tag.');
  }
  return '''
-- GENERATED by tool/generate_curriculum_seed.dart from
-- supabase/curriculum/journey-metadata.json. Do not edit by hand.
--
-- Publishes the curriculum's identifying metadata for the local church
-- through the real publish_curriculum() operation (ADR-019): cover
-- titles, themes, topics, section headings, scripture references and
-- Training Module titles. No lesson wording, Key Objectives, banners or
-- answers.

select public.publish_curriculum(
  'c0000000-0000-4000-8000-000000000001',
  $tag${definitionJson.trimRight()}$tag::jsonb,
  'METADATA',
  null,
  'a0000000-0000-4000-8000-000000000001'
);
''';
}
