// Builds each lesson's cover for the lesson list from the source PDFs.
//
//   dart run tool/curriculum/build_covers.dart
//
// Uses the ministry's own cover image when one is supplied in
// docs/curriculum/source/covers/ (git-ignored), named lesson-01.jpg to
// lesson-10.jpg (.jpeg, .png or .webp also work). Otherwise it takes the
// lesson's cover photo from the source PDF (the JPEG drawn on its title
// page; which image, in file order, is "cover" in lesson-NN.banners.json).
// It scales the image to 720 px wide, and writes supabase/curriculum/full/publish_covers.sql
// (git-ignored), which stores them for the local church through
// set_lesson_cover(). Apply it like publish_local.sql.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:image/image.dart' as img;

import 'convert_lesson.dart' show fullDir, sourcePdf;
import 'suggest_hints.dart' show bannersPath;

/// The JPEG (DCTDecode) image streams of a PDF, in file order.
List<Uint8List> jpegStreams(Uint8List pdf) {
  final s = latin1.decode(pdf);
  final out = <Uint8List>[];
  for (final m in RegExp(r'/Subtype\s*/Image').allMatches(s)) {
    final start = s.lastIndexOf(' obj', m.start);
    final dictEnd = s.indexOf('stream', m.start);
    if (start < 0 || dictEnd < 0) continue;
    if (!s.substring(start, dictEnd).contains('DCTDecode')) continue;
    var from = dictEnd + 'stream'.length;
    if (s.codeUnitAt(from) == 13) from++;
    if (s.codeUnitAt(from) == 10) from++;
    final end = s.indexOf('endstream', from);
    out.add(Uint8List.sublistView(pdf, from, end));
  }
  return out;
}

/// The ministry's own cover for lesson [n], if supplied.
File? suppliedCover(int n) {
  final name = 'lesson-${n.toString().padLeft(2, '0')}';
  for (final ext in ['jpg', 'jpeg', 'png', 'webp']) {
    final f = File('docs/curriculum/source/covers/$name.$ext');
    if (f.existsSync()) return f;
  }
  return null;
}

/// The SQL that stores [image] as lesson [n]'s cover, 720 px wide.
String coverSql(int n, img.Image image) {
  final small = img.copyResize(image, width: 720);
  final data = base64Encode(img.encodeJpg(small, quality: 72));
  return '''
select public.set_lesson_cover(
  (select l.id from public.curriculum_lessons l
     join public.curricula c on c.id = l.curriculum_id and c.status = 'ACTIVE'
   where c.church_id = 'c0000000-0000-4000-8000-000000000001'
     and l.lesson_number = $n),
  '$data'
);''';
}

void main() {
  final sql = StringBuffer()
    ..writeln(
      '-- GENERATED by tool/curriculum/build_covers.dart. Git-ignored.',
    );
  for (var n = 1; n <= 10; n++) {
    final supplied = suppliedCover(n);
    if (supplied != null) {
      final image = img.decodeImage(supplied.readAsBytesSync());
      if (image == null) {
        stderr.writeln('Lesson $n: ${supplied.path} does not decode');
        exitCode = 1;
        continue;
      }
      sql.writeln(coverSql(n, image));
      stdout.writeln('Lesson $n: supplied ${supplied.path}');
      continue;
    }
    final banners = (jsonDecode(File(bannersPath(n)).readAsStringSync()) as Map)
        .cast<String, dynamic>();
    final index = banners['cover'] as int?;
    if (index == null) {
      stderr.writeln('Lesson $n: no "cover" in its banners file');
      exitCode = 1;
      continue;
    }
    final streams = jpegStreams(File(sourcePdf(n)).readAsBytesSync());
    final decoded = img.decodeJpg(streams[index - 1]);
    if (decoded == null) {
      stderr.writeln('Lesson $n: cover image $index does not decode');
      exitCode = 1;
      continue;
    }
    // The book's photos are Adobe CMYK JPEGs, stored inverted; the decoder
    // does not undo that.
    sql.writeln(coverSql(n, img.invert(decoded)));
    stdout.writeln('Lesson $n: cover from the source PDF');
  }
  File('$fullDir/publish_covers.sql').writeAsStringSync(sql.toString());
}
